# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Introducción a Python Técnicas Informáticas en Física"
author: <a href="https://produccioncientifica.usal.es/investigadores/57777/detalle">María Navarro Cáceres</a> y <a href="https://produccioncientifica.usal.es/investigadores/148041/detalle">Álvaro Lozano Murciego</a>
#logo: logo.png
copyright: "2025"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
# Opciones: 'off' (no ejecuta), 'cache' (solo si cambian), 'force' (siempre ejecuta)
execute:
  execute_notebooks: off
  allow_errors: true

# Ensure latest myst-nb respects the no-execution policy
execution:
  execute_notebooks: off
  allow_errors: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/merismeris/python-TIF
  path_to_book: content  # Optional path to your book, relative to the repository root
  branch: mi-cambio  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_baseurl: true
  baseurl: /python-TIF/
  extra_css:
    - _static/myfile.css
  extra_footer: |
    <p>
    &copy; 2023-2025; CC-BY-NC-SA 4.0
    <p>

sphinx:
  config:
    html_show_copyright: false
    nb_execution_mode: "off"
  extra_extensions:
    - sphinx_accessibility

launch_buttons:
   thebe: true
   notebook_interface: "classic"
   colab_url: "https://colab.research.google.com"
   thebe_config:
      use_thebe_lite: true

parse:
  extensions:
    - myst_parser
    - sphinx_design

  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
    - linkify
    - colon_fence
